_target_: navsim.agents.pseudodrivelab.pseudodrivelab_agent.PseudodrivelabAgent
_convert_: 'all'

trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.5
config:
  _target_: navsim.agents.pseudodrivelab.pseudodrivelab_config.PseudodrivelabConfig
  _convert_: 'all'
  latent: true        # EDITTED: Using positional encoding, not lidar info. 
checkpoint_path: null
lr: 1e-4
